blog/articles/urls.py
from django.urls import path, include
from .views import index, show_articles, showarticle, show_topics, send_input_data, create_topic, create_article
from .views import show_cat, show_cake, show_tut, show_computer, show_underwater,show_weeds
app_name = 'articles'   #This is the app namespace

urlpatterns = [
    path('', index, name='index'),
    path('topics', show_topics, name='topics'),
    path('input', send_input_data, name='input'),
    path('topic/add', create_topic, name='add_topic'),
    path('article/create', create_article, name='create_article'),
    path('article/show', show_articles, name='show_articles'),
    path('cat', show_cat, name='show_cat'),
    path('cake', show_cake, name='show_cake'),
    path('tut', show_tut, name='show_tut'),
    path('computer', show_computer, name='show_computer'),
    path('underwater', show_underwater, name='show_underwater'),
    path('weeds', show_weeds, name='show_weeds'),
    #path('article', showarticle, name='articles')
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

namespace='blog'

urlpatterns = [
    path('admin/', admin.site.urls ),
    path('', include('articles.urls')),
]

blog/articles/models.py
from django.db import models

# Create your models here.


class Topic(models.Model):
    topic_name = models.CharField(max_length = 256)

    def __str__(self):
        return self.topic_name

class Article(models.Model):

    title = models.CharField(max_length =256)
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE, related_name='articles')
    articleText = models.TextField()
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

blog/articles/forms.py
from django import forms
from .models import Article, Topic


class InputForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()

class TopicForm(forms.ModelForm):
    class Meta():
        model = Topic
        fields = ("topic_name",)

class ArticleForm(forms.ModelForm):
    class Meta():
        model = Article
        exclude =['created_at',]

blog/articles/views.py
from django.shortcuts import render, redirect
from .models import Topic, Article #imported
from .forms import InputForm
from . import forms
#from django.http import HttpResponse



#   Create your views here.

def create_article(request):
    if request.method == "POST":
        form = forms.ArticleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:topics')
        else:
            print("an error has occured")
    form = forms.ArticleForm()
    return render(request, 'input.html', {'form':form})


def show_articles(request):
    articles = Article.objects.all()
    return render(request, 'index.html', {'articles':articles})


def create_topic(request):
    if request.method == "POST":
        form = forms.TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:topics')
        else:
            print("an error has occured")
    form = forms.TopicForm()
    return render(request, 'input.html', {'form':form})

def send_input_data(request):
    form = InputForm()
    if request.method == "POST":
        form = InputForm(request.POST)
        if form.is_valid():
            print("form valid")
        else:
            print("form not valid")
    return render(request,'input.html',{'form':form})

def show_topics(request):
    topics = Topic.objects.all()
    return render(request, 'topics.html', {'topics':topics})

def showarticle(request):
    title="My First Article"
    article="""
    Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
    """
    author = "Matshehla Konaite"
    return render(request, 'blog.html',{'title':title, 'article':article})

def show_cat(request):
    return render(request,'cat.html',{'form':''})

def show_cake(request):
    return render(request,'cake.html',)

def show_tut(request):
    return render(request,'graduations.html',)

def show_computer(request):
    return render(request,'computer.html',)

def show_underwater(request):
    return render(request,'underwater.html',)

def show_weeds(request):
    return render(request,'weeds.html',)

#testing
def index(request):
    return render(request,'index.html',)



#   Create your views here.
# def index(request):
#    return HttpResponse("AppTwo Index view")

blog/articles/templates/cake.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!--Student Name: Matshehla Mathews Konaite
        Student No: 213659103
        Lecturers: Dr. Kyle Stone and Mark Muwanguzi
        Course: Full Stack Web Development Short Learning Course
        Assignment 2
        Date: 30 October 2022
    -->

    <!-- Required meta tags -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="./css/bootstrap.min.css">
    <link rel="stylesheet" href="./css/custom.css">       <!-- This overwrite above bootstrap css. Because is put last
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <title>Blog: Assignmet 2</title>
  </head>
  <body>

    <div class="jumbotron jumbtron-fluid">
      <div class="container">
        <h1>MY BLOG</h1>
        <h6>Best stories by Matshehla Konaite
          <a href="admin/" class="btn btn-link" style="color:black; float:right">Admin</a>
          <a href="{% url 'articles:index' %}" class="btn btn-link" style="color:black; float:right">Home</a>
        </h6>
      </div>
    </div>


    <!-- let Bootstrap automatically handle the layout -->
    <div class="container">
      <a href="{% url 'articles:index' %}" class="btn btn-primary">Go to Home Page</a>
      <br>
      <br>
    </div>
    <div class="container">

      <div class="row">
        <div class="col">
          <div class="container">
            <div class="card img-fluid" style="width:100%">
              <img class="card-img-top" src="{% static 'images/cake.jpg' %}" alt="Card image" style="width:100%">
              <div class="card-img-overlay">
                <h4 class="card-title" style="color:white; background-color:black; text-align:center">Cake</h4>
              </div>
            </div>
            <br>

          </div>
        </div>
        <div class="col">
          <h2>Cake</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed id semper risus in. Tellus orci ac auctor augue mauris. Morbi tristique senectus et netus et malesuada fames. Pharetra magna ac placerat vestibulum. Nulla facilisi etiam dignissim diam quis. Cursus eget nunc scelerisque viverra mauris in. Aliquam ut porttitor leo a diam sollicitudin tempor id. Lobortis feugiat vivamus at augue eget. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. A cras semper auctor neque vitae tempus quam pellentesque nec. In nulla posuere sollicitudin aliquam ultrices sagittis orci a.

          Tellus rutrum tellus pellentesque eu. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Mattis rhoncus urna neque viverra justo nec ultrices. Feugiat nibh sed pulvinar proin gravida hendrerit. Imperdiet massa tincidunt nunc pulvinar sapien et. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Velit euismod in pellentesque massa placerat duis ultricies. Porttitor leo a diam sollicitudin tempor id eu nisl nunc. Nam at lectus urna duis convallis convallis tellus. Ornare arcu dui vivamus arcu felis. Tortor at risus viverra adipiscing at in tellus. Turpis in eu mi bibendum neque egestas congue quisque. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Nunc id cursus metus aliquam eleifend mi in. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Id aliquet risus feugiat in ante metus. Dignissim convallis aenean et tortor at risus viverra. At elementum eu facilisis sed.
          </p>
        </div>
      </div>
    </div>

    <br>

      <!--Footer -->
        <div class="container-fluid" style="background-color:rgb(220,220,220); margin-bottom:0rem">
          <br>
          <div class="container">
            <h1>Blogging</h1>
            <p>The blockquote element is used to present content of the Blog</p>
            <blockquote class="blockquote">
              <p>For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</p>
              <footer class="blockquote-footer">From WWF's website</footer>
            </blockquote>
          </div>
          <br>
        </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="./js/jquery.js"></script>
    <script src="./js/popper.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="./js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

blog/articles/templates/cat.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!--Student Name: Matshehla Mathews Konaite
        Student No: 213659103
        Lecturers: Dr. Kyle Stone and Mark Muwanguzi
        Course: Full Stack Web Development Short Learning Course
        Assignment 2
        Date: 30 October 2022
    -->

    <!-- Required meta tags -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="./css/bootstrap.min.css">
    <link rel="stylesheet" href="./css/custom.css">       <!-- This overwrite above bootstrap css. Because is put last
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <title>Blog: Assignmet 2</title>
  </head>
  <body>

    <div class="jumbotron jumbtron-fluid">
      <div class="container">
        <h1>MY BLOG</h1>
        <h6>Best stories by Matshehla Konaite
          <a href="admin/" class="btn btn-link" style="color:black; float:right">Admin</a>
          <a href="{% url 'articles:index' %}" class="btn btn-link" style="color:black; float:right">Home</a>
        </h6>
      </div>
    </div>


    <!-- let Bootstrap automatically handle the layout -->
    <div class="container">
      <a href="{% url 'articles:index' %}" class="btn btn-primary">Go to Home Page</a>
      <br>
      <br>
    </div>
    <div class="container">

      <div class="row">
        <div class="col">
          <div class="container">
            <div class="card img-fluid" style="width:100%">
              <img class="card-img-top" src="{% static 'images/cat.jpg' %}" alt="Card image" style="width:100%">
              <div class="card-img-overlay">
                <h4 class="card-title" style="color:white; background-color:black; text-align:center">Cat</h4>
              </div>
            </div>
            <br>

          </div>
        </div>
        <div class="col">
          <h2>Cat</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed id semper risus in. Tellus orci ac auctor augue mauris. Morbi tristique senectus et netus et malesuada fames. Pharetra magna ac placerat vestibulum. Nulla facilisi etiam dignissim diam quis. Cursus eget nunc scelerisque viverra mauris in. Aliquam ut porttitor leo a diam sollicitudin tempor id. Lobortis feugiat vivamus at augue eget. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. A cras semper auctor neque vitae tempus quam pellentesque nec. In nulla posuere sollicitudin aliquam ultrices sagittis orci a.

          Tellus rutrum tellus pellentesque eu. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Mattis rhoncus urna neque viverra justo nec ultrices. Feugiat nibh sed pulvinar proin gravida hendrerit. Imperdiet massa tincidunt nunc pulvinar sapien et. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Velit euismod in pellentesque massa placerat duis ultricies. Porttitor leo a diam sollicitudin tempor id eu nisl nunc. Nam at lectus urna duis convallis convallis tellus. Ornare arcu dui vivamus arcu felis. Tortor at risus viverra adipiscing at in tellus. Turpis in eu mi bibendum neque egestas congue quisque. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Nunc id cursus metus aliquam eleifend mi in. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Id aliquet risus feugiat in ante metus. Dignissim convallis aenean et tortor at risus viverra. At elementum eu facilisis sed.
          </p>
        </div>
      </div>
    </div>

    <br>

      <!--Footer -->
        <div class="container-fluid" style="background-color:rgb(220,220,220); margin-bottom:0rem">
          <br>
          <div class="container">
            <h1>Blogging</h1>
            <p>The blockquote element is used to present content of the Blog</p>
            <blockquote class="blockquote">
              <p>For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</p>
              <footer class="blockquote-footer">From WWF's website</footer>
            </blockquote>
          </div>
          <br>
        </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="./js/jquery.js"></script>
    <script src="./js/popper.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="./js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

blog/articles/templates/computer.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!--Student Name: Matshehla Mathews Konaite
        Student No: 213659103
        Lecturers: Dr. Kyle Stone and Mark Muwanguzi
        Course: Full Stack Web Development Short Learning Course
        Assignment 2
        Date: 30 October 2022
    -->

    <!-- Required meta tags -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="./css/bootstrap.min.css">
    <link rel="stylesheet" href="./css/custom.css">       <!-- This overwrite above bootstrap css. Because is put last
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <title>Blog: Assignmet 2</title>
  </head>
  <body>

    <div class="jumbotron jumbtron-fluid">
      <div class="container">
        <h1>MY BLOG</h1>
        <h6>Best stories by Matshehla Konaite
          <a href="admin/" class="btn btn-link" style="color:black; float:right">Admin</a>
          <a href="{% url 'articles:index' %}" class="btn btn-link" style="color:black; float:right">Home</a>
        </h6>
      </div>
    </div>

    <!-- let Bootstrap automatically handle the layout -->
    <div class="container">
      <a href="{% url 'articles:index' %}" class="btn btn-primary">Go to Home Page</a>
      <br>
      <br>
    </div>
    <div class="container">

      <div class="row">
        <div class="col">
          <div class="container">
            <div class="card img-fluid" style="width:100%">
              <img class="card-img-top" src="{% static 'images/computer.jpg' %}" alt="Card image" style="width:100%">
              <div class="card-img-overlay">
                <h4 class="card-title" style="color:white; background-color:black; text-align:center">Computer</h4>
              </div>
            </div>
            <br>

          </div>
        </div>
        <div class="col">
          <h2>Computer</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed id semper risus in. Tellus orci ac auctor augue mauris. Morbi tristique senectus et netus et malesuada fames. Pharetra magna ac placerat vestibulum. Nulla facilisi etiam dignissim diam quis. Cursus eget nunc scelerisque viverra mauris in. Aliquam ut porttitor leo a diam sollicitudin tempor id. Lobortis feugiat vivamus at augue eget. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. A cras semper auctor neque vitae tempus quam pellentesque nec. In nulla posuere sollicitudin aliquam ultrices sagittis orci a.

          Tellus rutrum tellus pellentesque eu. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Mattis rhoncus urna neque viverra justo nec ultrices. Feugiat nibh sed pulvinar proin gravida hendrerit. Imperdiet massa tincidunt nunc pulvinar sapien et. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Velit euismod in pellentesque massa placerat duis ultricies. Porttitor leo a diam sollicitudin tempor id eu nisl nunc. Nam at lectus urna duis convallis convallis tellus. Ornare arcu dui vivamus arcu felis. Tortor at risus viverra adipiscing at in tellus. Turpis in eu mi bibendum neque egestas congue quisque. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Nunc id cursus metus aliquam eleifend mi in. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Id aliquet risus feugiat in ante metus. Dignissim convallis aenean et tortor at risus viverra. At elementum eu facilisis sed.
          </p>
        </div>
      </div>
    </div>

    <br>

      <!--Footer -->
        <div class="container-fluid" style="background-color:rgb(220,220,220); margin-bottom:0rem">
          <br>
          <div class="container">
            <h1>Blogging</h1>
            <p>The blockquote element is used to present content of the Blog</p>
            <blockquote class="blockquote">
              <p>For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</p>
              <footer class="blockquote-footer">From WWF's website</footer>
            </blockquote>
          </div>
          <br>
        </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="./js/jquery.js"></script>
    <script src="./js/popper.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="./js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

blog/articles/templates/graduations.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!--Student Name: Matshehla Mathews Konaite
        Student No: 213659103
        Lecturers: Dr. Kyle Stone and Mark Muwanguzi
        Course: Full Stack Web Development Short Learning Course
        Assignment 2
        Date: 30 October 2022
    -->

    <!-- Required meta tags -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!--<link rel="stylesheet" href="./css/bootstrap.min.css">
    <link rel="stylesheet" href="./css/custom.css">       <!-- This overwrite above bootstrap css. Because is put last
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
-->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <title>Blog: Assignmet 2</title>
  </head>
  <body>

    <div class="jumbotron jumbtron-fluid">
      <div class="container">
        <h1>MY BLOG</h1>
        <h6>Best stories by Matshehla Konaite
          <a href="admin/" class="btn btn-link" style="color:black; float:right">Admin</a>
          <a href="{% url 'articles:index' %}" class="btn btn-link" style="color:black; float:right">Home</a>
        </h6>
      </div>
    </div>

    <!-- let Bootstrap automatically handle the layout -->
    <div class="container">
      <a href="{% url 'articles:index' %}" class="btn btn-primary">Go to Home Page</a>
      <br>
      <br>
    </div>
    <div class="container">

      <div class="row">
        <div class="col">
          <div class="container">
            <div class="card img-fluid" style="width:100%">
              <img class="card-img-top" src="{% static 'images/graduations.jpg' %}" alt="Card image" style="width:100%">
              <div class="card-img-overlay">
                <h4 class="card-title" style="color:white; background-color:black; text-align:center">Graduations at TUT</h4>
              </div>
            </div>
            <br>

          </div>
        </div>
        <div class="col">
          <h2>Graduations at TUT</h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed id semper risus in. Tellus orci ac auctor augue mauris. Morbi tristique senectus et netus et malesuada fames. Pharetra magna ac placerat vestibulum. Nulla facilisi etiam dignissim diam quis. Cursus eget nunc scelerisque viverra mauris in. Aliquam ut porttitor leo a diam sollicitudin tempor id. Lobortis feugiat vivamus at augue eget. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. A cras semper auctor neque vitae tempus quam pellentesque nec. In nulla posuere sollicitudin aliquam ultrices sagittis orci a.

          Tellus rutrum tellus pellentesque eu. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Mattis rhoncus urna neque viverra justo nec ultrices. Feugiat nibh sed pulvinar proin gravida hendrerit. Imperdiet massa tincidunt nunc pulvinar sapien et. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Velit euismod in pellentesque massa placerat duis ultricies. Porttitor leo a diam sollicitudin tempor id eu nisl nunc. Nam at lectus urna duis convallis convallis tellus. Ornare arcu dui vivamus arcu felis. Tortor at risus viverra adipiscing at in tellus. Turpis in eu mi bibendum neque egestas congue quisque. Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Nunc id cursus metus aliquam eleifend mi in. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Id aliquet risus feugiat in ante metus. Dignissim convallis aenean et tortor at risus viverra. At elementum eu facilisis sed.
          </p>
        </div>
      </div>
    </div>

    <br>

      <!--Footer -->
        <div class="container-fluid" style="background-color:rgb(220,220,220); margin-bottom:0rem">
          <br>
          <div class="container">
            <h1>Blogging</h1>
            <p>The blockquote element is used to present content of the Blog</p>
            <blockquote class="blockquote">
              <p>For 50 years, WWF has been protecting the future of nature. The world's leading conservation organization, WWF works in 100 countries and is supported by 1.2 million members in the United States and close to 5 million globally.</p>
              <footer class="blockquote-footer">From WWF's website</footer>
            </blockquote>
          </div>
          <br>
        </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="./js/jquery.js"></script>
    <script src="./js/popper.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="./js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>